### ISSUE TITLE
FEATURE REQUEST: Add to side panel 

### ISSUE THREAD

**Issue by jclsn** [diyhue/hassio-addon#1]
It would be nice to have diyHue in the side panel instead of opening it separately in the browser.

**Comment by jclsn** [comment]
@Mevel some apps have switch that says "add to side panel", which embeds diyHue in HA, so I guess the first option.

**Comment by Mevel** [comment]
I looked into it and it is the ingress option for add-ons. Need some research and implement it if possible

**Comment by Mevel** [comment]
There is no fast way as of now. Best is to add a iframe to the diyhue Web ui

`panel_iframe:
  diyhue:
    title: "diyHue"
    icon: mdi:home-lightbulb
    url: "http://homeassistant:80"`

**Comment by jclsn** [comment]
No that doesn't work. You can't embed a http address into an SSL secured HA instance. You need a reverse proxy.
