### ISSUE TITLE
Can't find addon in Store

### ISSUE THREAD

**Issue by thomasfjen** [diyhue/hassio-addon#13]
After adding the repo to my home assistant i can't find the addon in the addon page to install it. Is it not compatible anymore?
Newst Home Assistant version, x64 official ha nice image.

**Comment by a-jey** [comment]
Did you restart HA?
It appeared after that in my case.

![grafik](https://user-images.githubusercontent.com/72740604/218599393-e60e19f3-22ee-456f-93ea-18bee3ef3845.png)

**Comment by thomasfjen** [comment]
I restarted a few times, but looking in the store now it appaered!
