### ISSUE TITLE
Not loading/reinstalling after switch from RPi to VM on NAS

### ISSUE THREAD

**Issue by terrorhai** [diyhue/hassio-addon#16]
Hey,
first, thanks for the awesome work, I used the add on for a long time on my RPi 4 with Home Assistant!
Now I tried to move my Home Assistant from a full backup to my NAS into a Virtual Box VM running Home Assistant OS. Everything works fine, except the diyhue addon. The NAS is an ASUSTOR AS6704T, so plenty of power.

When trying to rebuild or reinstall I get this error:
The command '/bin/bash -o pipefail -c curl -J -L -o $diyhue.tar.gz "https://github.com/diyhue/diyHue/archive/refs/heads/master.tar.gz" && tar xzvf $diyhue.tar.gz --strip-components=1 -C diyhue && rm -rf $diyhue.tar.gz && pip3 install -r /diyhue/requirements.txt --no-cache-dir' returned a non-zero code: 1 

I don't know what I have to do to fix this error....help ;-)

EDIT: I tried to set up a fresh Home Assistant install and the add on installation gives me the same error.

**Comment by mariusmotea** [comment]
Unfortunately you have only an exit code there and not the error. What you execute are multiple commands in one line. Try to execute manually every command to see where it fails. The `&&` is the delimiter between the commands.

**Comment by Bx16** [comment]
Hello, I got same error in HA, manual install :
[https://i.imgur.com/C0RumFQ.png](url)

**Comment by terrorhai** [comment]
> Hello, I got same error in HA, manual install : https://i.imgur.com/C0RumFQ.png

Had to manually install python and pip3 because it wasn't installed.
I did the manual way too and got the exact same error message.

**Comment by terrorhai** [comment]
Hey Marius, I made a new setup of home assistant on my NAS yesterday, restored my backup from the Pi and now everything installed successfully. Had no problems with DIYhue at all, it just installed from the backup and everything works fine.
