### ISSUE TITLE
Home assistant light brightness not controllable

### ISSUE THREAD

**Issue by jclsn** [diyhue/hassio-addon#2]
I could get it to connect to HA now. The lights are showing up. I can turn the lights on and off but not change colors or brightness.

EDIT: I can control one Ledvance LED color, but not the brightness. The brightness of another Hue Lamp also doesn't work. Actually this shouldn't matter because they are all exposed by HA.

**Comment by chillkiller** [comment]
You need to edit the hardware (Bulb, strip, plug, white, color... etc.) in diyhue ui

**Comment by jclsn** [comment]
How? I only have this. There are no options really. I can just change IDs.

![grafik](https://user-images.githubusercontent.com/19779511/167458289-d3399266-1b8b-4dd2-9cda-2b21b9290e32.png)

**Comment by jclsn** [comment]
I think those are the IDs of the devices.

**Comment by chillkiller** [comment]
if you click on the LCT015 you can change it... Its the ID of if it is a plug or a rgb bulb, but I don't know what is what of it

**Comment by chillkiller** [comment]
> LWB010 = Hue white LTW001 = Hue white ambiance LST002 = Hue light strip plus LCT001 = Hue white and color ambiance LCT015 = Hue white and color ambiance (new version probably)
> 
> Ja funktioniert nicht wirklich gut leider. Ist wohl besser die Lampen direkt zu verbinden

So u will get into an other issue... HA deconz addon isn't pairing with HA diyhue addon at the moment

This is my issue for now, can't pairing deconz and can't pairing my Philips ambilight TV

If this will work I connect all to deconz and pair it with diyhue and than let my TV control the Lights by diyhue ;)

also diyhue addon doesn't get my motion sensors of hue whats not so bad as I use node-red to control them and to temporary switch off the ambilight+hue if I'm in the kitchen (Wohnkücke)...

**Comment by chillkiller** [comment]
thx for the list

**Comment by jclsn** [comment]
Why 2m away? I have a Conbee stick II which has a really long range. It should work in the same room

**Comment by Mevel** [comment]
Congee is the zigbee gateway, deconz the managing software.
You need to add the bulbs to your zigbee network via decobz.

After that you can import the lights and sensors to diyhue

**Comment by jclsn** [comment]
@Mevel I went with zigbee2mqtt and it works well. 

I also discovered Hyperion yesterday and am currently trying to get it to work with diyHue. Some responses are not correct. Well, off topic...

**Comment by Mevel** [comment]
@chillkiller we usually connect to the websocket of deconz directly.

You can configure it in the diyhue web ui

**Comment by jclsn** [comment]
I had success with MQTT. Never tried Deconz. I only wanted it for TV syncing, but now found Hyperion which does a much better job with wifi bulbs. Would still be nice with Zigee bulbs though, but the HA API support is buggy and MQTT is not fast enough.

**Comment by chillkiller** [comment]
@jclsn 
my lights all zigbee, my tv is Philips ambilight, that dont work for me and is also not my goal... I only want to get out of the Philips Hue bridge (limitation of 50 devices per bridge) but all should still work as used last few years, so my goal is to pair deconz (HA addon) with DIYHue Bridge (HA Addon) and setup all like before...

Little tip, you can also use ha integration directly instead mqtt, could be little bit faster

![grafik](https://user-images.githubusercontent.com/61262352/174186636-30816d6e-4454-4252-b5e5-69fff83cd78e.png)

**Comment by jclsn** [comment]
It would be faster if I weren't using zigbee2mqtt. Havent configured ZHA yet and the HA API support of diyHue doesn't work obviously.

**Comment by foxy82** [comment]
Original issue is likely to be due to this:
https://github.com/diyhue/diyHue/issues/741

**Comment by foxy82** [comment]
Original issue is likely to be due to this:
https://github.com/diyhue/diyHue/issues/741

**Comment by jclsn** [comment]
Yes, that sounds like the issue

**Comment by foxy82** [comment]
Issue is fixed in the latest add on version - as well as bulbs should be detected better.

**Comment by jclsn** [comment]
@Mevel I think you need to update the version somehow, because Home Assistant doesn't notify about an update

**Comment by foxy82** [comment]
Mine did - go into the Add ons and click the "Add On Store" button. Then hit the 3 dots and "Check for updates" that will force it through.

**Comment by jclsn** [comment]
Ah for me another installation option popped up, but no update was shown. I updated it now by uninstalling the old addon. Unfortunately I can't get diyHue to connect to HA anymore

**Comment by foxy82** [comment]
Raise an issue on diyhue and I can look into it - it is working for me.
