### ISSUE TITLE
Certificate can't be generated on first boot. (Supervisor)

### ISSUE THREAD

**Issue by XXBrain** [diyhue/hassio-addon#20]
Hello. 

I just started with a fresh HA Supervisor installation to use this stunning peace of software. Unfortunatly DIY Hue fails to create the cert.pem on startup.

Steps to reproduce:
- import Supervisor VM in DSM with current image from HA Homepage
- install DIY Hue addon
- change MAC Address setting to the virtual machine ones
- start the addon

See the attached log. It complains about a missing faketime and afterwards the crt and key files. 

Home Assistant 2023.10.0 
Supervisor 2023.10.0 
Operating System 10.5

[diyhue.log](https://github.com/diyhue/hassio-addon/files/12835148/diyhue.log)

Do I miss something?

**Comment by XXBrain** [comment]
I tried to install libfaketime inside the container, wich takes forever. Signatures of repsitories are not trusted and after each restart the container seems to be resettet again and libfaktime is missing again.

**Comment by mariusmotea** [comment]
I think we need to update something to HAOS manifests. @Mevel any idea?

**Comment by thommy86** [comment]
Is there a workaround for this? The curl option is giving me an empty response:

curl "http://mariusmotea.go.ro:9002/gencert?mac=00:11:22:33:44:55" -v

**Comment by XXBrain** [comment]
I've created a cert within a docker container (version 922) with its own ip, using the same mac address and replaced the file in the hassio addon config folder with that one.

OT: I would propose to pair the Philips Hue with that docker container, too and copy the login entry form the config file. Use 922. I could not pair with the current version, because the app asks for a second push after finding the diyHue bridge, wich one could not press.

**Comment by sosheskaz** [comment]
Also seeing no `faketime` binary.
