### ISSUE TITLE
Add-on failed to install

### ISSUE THREAD

**Issue by sajtos888** [diyhue/hassio-addon#33]
I get an error during installation. I get the same error on a new HA installation, test machine. 
All other add-ons are successfully installed by HA.

The command '/bin/bash -o pipefail -c apk --no-cache add --virtual build-deps gcc git make musl-dev && git clone https://github.com/wolfcw/libfaketime && cd libfaketime && make && mv src/*.so* /lib && mv src/faketime /bin && cd - && rm -rf libfaketime && apk del build-deps' returned a non-zero code: 2

Thank You.

**Comment by hendriksen-mark** [comment]
This is a faketime issue not a diyhue issue.
https://github.com/wolfcw/libfaketime/issues/467

**Comment by sajtos888** [comment]
Ok. Wait :) thanks.

**Comment by hendriksen-mark** [comment]
can you try install it now?

**Comment by sajtos888** [comment]
now the error is different.
The command '/bin/bash -o pipefail -c git checkout v0.9.10 && make && mv src/*.so* /lib && mv src/faketime /bin && cd - && rm -rf libfaketime && apk del build-deps' returned a non-zero code: 1

**Comment by andisp01** [comment]
> now the error is different. The command '/bin/bash -o pipefail -c git checkout v0.9.10 && make && mv src/_.so_ /lib && mv src/faketime /bin && cd - && rm -rf libfaketime && apk del build-deps' returned a non-zero code: 1

I have the exact same error.

**Comment by hendriksen-mark** [comment]
can you try again?

**Comment by sajtos888** [comment]
it works. :)

**Comment by andisp01** [comment]
it works for me too :)
thanks
