### ISSUE TITLE
diyhue can't install

### ISSUE THREAD

**Issue by N19aSASa58N** [diyhue/hassio-addon#36]
pls help me with install with this error

The command '/bin/bash -o pipefail -c git checkout v0.9.10 && make && mv src/*.so* /lib && mv src/faketime /bin && cd - && rm -rf libfaketime && apk del build-deps' returned a non-zero code: 1

**Comment by macmonty** [comment]
Same error for me

**Comment by churchofnoise** [comment]
Same error here when trying to update from 2.0.13 to 2.0.14

**Comment by hendriksen-mark** [comment]
please try installing now.
it works on my test HA installation.

**Comment by churchofnoise** [comment]
> please try installing now.
> it works on my test HA installation.

Solved here

**Comment by N19aSASa58N** [comment]
> > please try installing now.
> > it works on my test HA installation.
> 
> Solved here

worked
