### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Pixelramp** [diyhue/hassio-addon#39]
Hello,

i'm unable to install the diyHue add-on in Home assistant.

Running a fresh installation on Raspberry Pi 4.

Error when installing diyHue : 

The command '/bin/bash -o pipefail -c mv /diyhue/BridgeEmulator/web-ui/ ./web-ui/' returned a non-zero code: 1

Error when installing diyHUE Beta:

The command '/bin/bash -o pipefail -c curl -J -L -o $diyhue.tar.gz "https://github.com/diyhue/diyHue/archive/refs/heads/beta.tar.gz" && tar xzvf $diyhue.tar.gz --strip-components=1 -C diyhue && rm -rf $diyhue.tar.gz && pip3 install -r /diyhue/requirements.txt --no-cache-dir' returned a non-zero code: 2

**Comment by hendriksen-mark** [comment]
How do you install diyhue? The folder web-ui is gone for a few years now.

**Comment by Pixelramp** [comment]
> How do you install diyhue? The folder web-ui is gone for a few years now.

I've added the repository and tried to install it via the addon store.

**Comment by hendriksen-mark** [comment]
Did you add "https://github.com/diyhue/hassio-addon" to the repository in the store?

**Comment by Pixelramp** [comment]
> Did you add "https://github.com/diyhue/hassio-addon" to the repository in the store?
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/dbd241aa52031ee452058a5aeea72415b22138b17a8c68b218f538925b10733a/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f323330656230646437326335656235316630386163626439663734313662336265343761623237373866303431326661643739343462383733623232643832632f6469796875652f68617373696f2d6164646f6e"><img alt="" height="14" src="https://camo.githubusercontent.com/95e35b1ddbd18e9680ef4876f3544fdf46e2116b5fefc3f6a48e1e427ea75b59/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - diyhue/hassio-addon](https://github.com/diyhue/hassio-addon)**Contribute to diyhue/hassio-addon development by creating an account on GitHub.

Yea my bad, somehow copied the wrong repository. Works now! Sorry, my bad! Thank you!
