### ISSUE TITLE
Ngnix proxy manager issue

### ISSUE THREAD

**Issue by strusic** [diyhue/hassio-addon#4]
Addon just didnt work when running ngnix proxy manager addon. Is it possible to get this working? Ive tried to compile it myself with other ports, and its half way working, controling with web ui workd, but cant connect to bridge with other apps.

**Comment by Mevel** [comment]
Original hue apps require bridge to run on port 80 and 443. This might interfere with your proxy

**Comment by strusic** [comment]
So is there any solution to use them both? I need nginx to remote access :/

**Comment by Mevel** [comment]
can you remap your nginx proxy and free up 80 and 443?

**Comment by strusic** [comment]
Well... I spent about 3 days trying how to get this working and forgot to add new port in mobile app.
Just to be clear:
  - change ports in nginx proxy manager
  - forward those ports
  - change remote addres with new ssl port
Remote access to hassio is working now, and diyhue too.
Sorry to bother you.
