### ISSUE TITLE
Update 2.0.21 fails

### ISSUE THREAD

**Issue by Olli2k** [diyhue/hassio-addon#44]
For me updating to 2.0.21 is not possible. Core log entry:

Failed to to call /store/addons/c863ef44_diyhue/update - The command '/bin/bash -o pipefail -c cp -r /diyhueUI/dist/index.html /opt/hue-emulator/flaskUI/templates/' returned a non-zero code: 1

System: 
Core: 2024.11.2
HAOS on Proxmox

**Comment by hendriksen-mark** [comment]
Hi can you try again?

**Comment by bobbinz** [comment]
Ah, I am also having the same issue over at https://github.com/diyhue/diyHue/issues/1051

**Comment by bobbinz** [comment]
Seems to be related to the fact that in the release candidate /diyhueUI/dist/index.html does not exist

**Comment by hendriksen-mark** [comment]
I made a change, did you try it in the last 30 minutes?

**Comment by emog** [comment]
I tried now and it's the same

**Comment by hendriksen-mark** [comment]
please try 2.0.22

**Comment by emog** [comment]
It's the same: Failed to perform the action update/install. Error updating diyHue: The command '/bin/bash -o pipefail -c cp -r diyhueUI/dist/index.html /opt/hue-emulator/flaskUI/templates/' returned a non-zero code: 1 even with 2.0.22. Keep installing but at the end we got this error

**Comment by bobbinz** [comment]
Had to force a refresh.

Now get this error:

`The command '/bin/bash -o pipefail -c cp -r diyhueUI/dist/index.html /opt/hue-emulator/flaskUI/templates/' returned a non-zero code: 1
`

Seems to be the same:

```
cp: can't stat 'diyhueUI/dist/index.html': No such file or directory
 ---> Removed intermediate container 4c853f9bfcd8
```

**Comment by Bx16** [comment]
.22 installation:
`Step 31/49 : RUN cp -r diyhueUI/dist/index.html			/opt/hue-emulator/flaskUI/templates/
 ---> Running in 0528823093dc
cp: can't stat 'diyhueUI/dist/index.html': No such file or directory`

**Comment by hendriksen-mark** [comment]
its not the same error but similar, please try 2.0.23

**Comment by emog** [comment]
2.0.23 - The command '/bin/bash -o pipefail -c cp -r /diyhueUI/dist/index.html /opt/hue-emulator/flaskUI/templates/' returned a non-zero code: 1

**Comment by emog** [comment]
![Screenshot 2024-11-18 at 15 44 48](https://github.com/user-attachments/assets/db0b8fd0-815e-4421-85a4-9ce46d162df0)

**Comment by hendriksen-mark** [comment]
try 2.0.24

**Comment by emog** [comment]
![Screenshot 2024-11-18 at 15 54 58](https://github.com/user-attachments/assets/aff5bc21-6635-4096-976a-4e20bbfb718d)

**Comment by dvdkruk** [comment]
Tried 2.0.24, here is the full error log:
```sh
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:135
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 4:08:33 PM (3 occurrences)
Last logged: 6:33:26 PM

Failed to to call /store/addons/c863ef44_diyhue/update - The command '/bin/bash -o pipefail -c cp -r diyhueUI/dist/index.html /opt/hue-emulator/flaskUI/templates/' returned a non-zero code: 1
Failed to to call /store/addons/c863ef44_diyhue/update - The command '/bin/bash -o pipefail -c cp -r dist/index.html /opt/hue-emulator/flaskUI/templates/' returned a non-zero code: 1
```

**Comment by Nismonx** [comment]
Attempting to install the update will return error:404 when trying to access DIYhue app in web browser after update fail:

 
```
2024-11-18 18:18:39,925 - services.stateFetch - 27 - WARNING - Fireplace_seg0 is unreachable: <urlopen error [Errno 113] Host is unreachable>
2024-11-18 18:18:40,256 - werkzeug - 225 - INFO - 192.168.1.71 - - [18/Nov/2024 18:18:40] "GET / HTTP/1.1" 200 -
2024-11-18 18:18:40,353 - werkzeug - 225 - INFO - 192.168.1.71 - - [18/Nov/2024 18:18:40] "GET /static/js/main.f1ff5a61.js HTTP/1.1" 404 -
2024-11-18 18:18:40,363 - werkzeug - 225 - INFO - 192.168.1.71 - - [18/Nov/2024 18:18:40] "GET /static/css/main.567f9119.css HTTP/1.1" 404 -
2024-11-18 18:18:42,997 - services.stateFetch - 27 - WARNING - Fireplace_seg1 is unreachable: <urlopen error [Errno 113] Host is unreachable>
```

Manually restarting the addon will fix access to the web app as before.

Maybe I'm stating the obvious, but may help someone.

**Comment by hendriksen-mark** [comment]
Can someone try the remove the addon and reinstall it?

**Comment by Burn-In** [comment]
Remove and reinstall didn't work, stops with the same error.
Restoring a partial backup works.

**Comment by Nismonx** [comment]
I have HA running barebones on a rpi4, it's my test rig.
I'll try a clean install there in a little bit.

**Comment by Nismonx** [comment]
Clean install in a barabones system works fine.
![Uploading Screenshot_20241118_203132_Chrome.jpg…]()

**Comment by hendriksen-mark** [comment]
I made a work around, i think the problem is that HA is using a cached file for the zip files and not the latest from github.
Please try 2.0.25 with hardcored version/releases.

**Comment by dvdkruk** [comment]
@hendriksen-mark good find! This solved it for me. 
![image](https://github.com/user-attachments/assets/65eda751-73a4-41e9-bf76-cbe2f6548014)

**Comment by Nismonx** [comment]
Worked a treat for me :)
From 2.0.20 to 2.0.25

Good job Mark 👏 
Thanks for caring

**Comment by hendriksen-mark** [comment]
good to hear and thanks for the fast feedback.
