### ISSUE TITLE
Running HAOS on PROXMOX with two IP-addresses

### ISSUE THREAD

**Issue by daath** [diyhue/hassio-addon#45]
I was using port 80 and 443 for Home Assistant and other stuff, so what I thought I'd do is add another network interface to my virtual machine in PROXMOX - it works fine - it generated a new MAC and my DHCP-server supplied an IP.
I updated the diyhue config with the new MAC and then I went into the Home Assitant config directory and modified diyhue/config.yaml and changed "ipaddress" from the old HA-IP to the new IP. However, when I start the addon it still uses the old IP and therefore fails.
What do I need to do?

**Comment by hendriksen-mark** [comment]
The ip in the config file is not used for diyhue, it only there for the hue app, to change this you need to pass a variable to diyhue, this is currently not in HA, I will add this to the config page.

**Comment by daath** [comment]
Excellent. Thank you - I look forward to trying diyhue in the future.
It seemed to me that the port 80/443 requirement was most easily "fixed" by just adding a new network interface and using that :)

**Comment by hendriksen-mark** [comment]
The hue app needs port 80 and 443, changing the port will result in the hue app not working, you can change the ports of diyhue but then you need to bind the ports to the outside to 80 and 443.

**Comment by hendriksen-mark** [comment]
in the latest version you can change the ip setting.

**Comment by daath** [comment]
I haven't tested it, but I will assume that this fixes the problem I was having. Thank you!
