### ISSUE TITLE
Can't disable the HTTPS port

### ISSUE THREAD

**Issue by foxy82** [diyhue/hassio-addon#5]
Before the rewrite of diyhue we could run diyhue with --no-serve-https so that the HTTPS server isn't started.

In the addon the parameter can still be set but it is ignored. 

It looks like we need to add it as an env variable in run.sh and then in HueEmulator3.py we need to get that environment variable and add an if around the line that creates the HTTPS port.

At alternative (and possibly better) solution would be to make the HTTP / HTTPS ports configurable this is important as the addon runs in host network mode.

**Comment by foxy82** [comment]
Submitted a PR to look at / test. It mostly works for me except I think the Home Assistant connection isn't working perfectly.

I also often get "connecting" appearing using the diyhue app - I assume this isn't related to the change but it would be good to get confirmation.

**Comment by Mevel** [comment]
[17cfc30](https://github.com/diyhue/hassio-addon/commit/17cfc30b1d1ecddf9b13f32bee04dff695c5a773)

Was merged.

HA issue is looked into
